### ISSUE TITLE
Kind request for additional logic

### ISSUE THREAD

**Issue by oleg-work** [aleksandar-j/set-added-date#1]
Hello,

Thanks for your time, this plugin is almost what I was looking for. Can I ask you to implement some additional logic? What I propose:

1. Is it possible to show full date of creation, i.e. '2022-12-04 14:59:59' instead of '2022-12-04' while browsing cards?
2. Is it possible to make some arithmetic on these timestamps for example I want to select some cards and +/- = 10 seconds to each card's creation timestamps.

Why? I think these changes would solve problem of cards order for people who are interested in logical order of the cards. For example, initially I created 10 cards, which are in order of date added. Logically they have order of subject I was listening to. Later I want to add another card in between of cards 5-6, therefore I need to see full timestamps of card 5 and 6 (that's number 1 issue). Also we can imagine possibility of corner case when there is no space between card 5 ('2022-12-04 14:59:59') and card 6 ('2022-12-04 15:00:00'), then it would be cool to be able to shift all cards in current deck by 10 seconds (i.e. create space for additional 10 cards, that's issue number 2). 

With kind regards,
Oleg

**Comment by aleksandar-j** [comment]
Hi! Yes, I can definitely complete number 2 and will update the addon here and on AnkiWeb soon. I think something similar to the way I did it in my other add-on (Set Card Ease) should be fine. I am unable to do number 1 because it feels out of scope and could potentially break other addons. Adding that information to the tooltip (when changing the added date on a single card, similar to the feature in Set Card Ease) should be easy enough though.

**Comment by oleg-work** [comment]
Great, thanks. I want to argue about number 1 issue being out of scope, because underlying type is timestamp, not a date and I highly doubt that will be a subject to a change, therefore (at least for me?) it feels like a limitation, because we are manipulating timestamp data under the hood. I respect your concerns about other's people work and compatibility, but I've never seen any addon that does anything with `browse` menu and it's hard to imagine a useful one, which could be in a conflict with requested functionality. On the other hand I must admit that I've only superficial idea about the subject we are talking about and that's just my point of view.

**Comment by aleksandar-j** [comment]
Underlying type shouldn't change but I think that changing the look of the browser is better done through another addon created specifically for that purpose so users can pick and choose. I will look into it during the coming weekend. In the meantime, I've updated the addon here and on AnkiWeb. Please let me know what you think.
