### ISSUE TITLE
problem of last update 

### ISSUE THREAD

**Issue by muhelal** [aleksandar-j/set-added-date#2]
it would be deeply appreciated if you send me the old  version of  "set added date" because after the last update of "set added date" of anki, the add ons stopped working, I always receive the following message:
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 5.15.2 PyQt 5.15.5
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-12-12 21:52:25
Add-ons possibly involved: ⁨Set Added Date⁩

Caught exception:
Traceback (most recent call last):
  File "/home/muhammad/.local/share/Anki2/addons21/1124670306/__init__.py", line 10, in <lambda>
    actionSetAddedDate.triggered.connect(lambda: set_added_date.setAddedDate(browser))
  File "/home/muhammad/.local/share/Anki2/addons21/1124670306/set_added_date.py", line 93, in setAddedDate
    mw.col.db.execute("UPDATE notes SET id=? WHERE id=?", note_id_to_new_date[note_id], note_id)
  File "anki.dbproxy", line 67, in all
  File "anki.dbproxy", line 61, in _query
  File "anki._backend", line 82, in db_query
  File "anki._backend", line 106, in _db_command
anki.errors.DBError: DbError { info: "SqliteFailure(Error { code: ConstraintViolation, extended_code: 1555 }, Some(\"UNIQUE constraint failed: notes.id\"))", kind: Other }
Please help

**Comment by aleksandar-j** [comment]
I was able to reproduce the error and hopefully fix it for this next update. Can you try it out and confirm that it works as expected now? Anki is sometimes slow with addon updates but you can press "Check for Updates" button in the "Tools->Add-ons" menu to get it faster.

**Comment by muhelal** [comment]
thanks a lot, the last update works perfectly now.

i would like to pay your attention to another problem, when I try to change
the added date to cards I previously studied in an earlier date, I always
fail. I get a resemble message to the following"

Card with ID '1654949934405' has review(s) before new added date.
Aborting.". is there any way to succeed?.


Thanks

**Comment by aleksandar-j** [comment]
I have updated the addon once more. Although it still displays the warning, it now allows you to continue regardless.

**Comment by muhelal** [comment]
Awesome, thanks!
